### ISSUE TITLE
How to get the power consumed by the Coral Dev Board?

### ISSUE THREAD

**Issue by Olivier-Dopeli** [google-coral/tflite#11]
Hi,

I would like to get the inference/watts value of the different neural networks I would implement on the Coral Dev Board. 
I was able to find the measurement of the temperature (cat /sys/class/thermal/thermal_zone0/temp) but not the power consumption.

Can someone tell me how to get the power consumed when running a program on the Coral Dev Board?

Thank you in advance.

**Comment by Namburger** [comment]
@Olivier-Dopeli 
Unfortunately, there are no api for measuring power consumsion via software. You may get an estimate via [powertop](https://wiki.archlinux.org/index.php/Powertop) but to get accurate measurements, I suggest getting a wall outlet power meter.

**Comment by Olivier-Dopeli** [comment]
Hi,
Thanks for your prompt response.
If I understand correctly, the Coral Dev Board has no internal measurement of its power consumption and therefore there is no way to go through a simple command line.

**Comment by Namburger** [comment]
That's correct, thanks
