### ISSUE TITLE
No objects detected on retrained object detector guide

### ISSUE THREAD

**Issue by jdcast** [google-coral/tflite#12]
I'm trying to execute the retrained object detector obtained by this [google coral guide](https://coral.ai/docs/edgetpu/retrain-detection/) on the Coral USB Accelerator connected to a Raspberry Pi 3 B+.

Unfortunately, I just get the following output when trying to run the compiled model using the `detect_image.py` script installed in the [device setup guide](https://coral.ai/docs/accelerator/get-started/#setup-for-linux-or-raspberry-pi):
```
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
183.87 ms
23.69 ms
24.81 ms
36.91 ms
31.02 ms
-------RESULTS-------
No objects detected
```

The command I'm using on the rpi from within the installed github codebase directory from the device setup guide above (`~/coral/tflite/python/examples/detection/`) is:
```
python3 detect_image.py --model ~/output_tflite_graph_edgetpu.tflite --input ./images/dog.jpg
```

`dog.jpg` is the dog image supplied by the retraining an object detector guide above.

I noticed the retraining guide is a little out of date wrt the device setup guide.
Is there any work around to get the retraining guide to work?

Thanks!

EDIT:
I want to clarify that the above output is only when attempting to retrain MobileNet v1 (the model version used in the retraining guide above) but I do get some detection output when instead retraining MobileNet v2 as show below (though it seems wrong?):
![dog_result](https://user-images.githubusercontent.com/2231240/74504163-20346b80-4ea8-11ea-938a-3ae78250dd46.jpg)

Furthermore, I'm able to get the following reasonable outputs when simply running the MobileNet v1 and MobileNet v2 .tflite models respectively without any retraining (available [from the google coral model repo](https://coral.ai/models/)):
![dog_result_v1](https://user-images.githubusercontent.com/2231240/74505815-f29df100-4eac-11ea-873e-131d4ea92eb2.jpg)
![dog_result_v2](https://user-images.githubusercontent.com/2231240/74506000-6d670c00-4ead-11ea-9eb1-a04311f29cb6.jpg)

**Comment by Namburger** [comment]
Hi @jdcast sorry for the late response, I somehow did not see this query o_0
Similar to the classification retrain, we have plan to deprecate this tutorial, open source it and provide a colab version, this is why you see it's out dated. As for the issue, what `NUM_TRAINGING_STEPS` and `NUM_EVAL_STEPS` did you set?

**Comment by wangyihuan123** [comment]
I got the same issue. @Namburger 
I set ```NUM_TRAINING_STEPS=50000 && NUM_EVAL_STEPS=2000``` but stopped the training when ckpt got 7952 as mAP hadn't improved for a long time.
```
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.17s).
Accumulating evaluation results...
DONE (t=0.03s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.707
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.959
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.840
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.742
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.749
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.749
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.749
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.525
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.784
creating index...
index created!
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.17s).
Accumulating evaluation results...
DONE (t=0.03s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.725
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.959
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.862
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.762
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.758
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.764
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.764
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.525
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.801
```

On coral device, it couldn't detect any thing.
```
python3 detect_image.py   --model ${HOME}/ssd_mobilenet_v1_catsdogs_quant_edgetpu.tflite   --labels ${HOME}/labels.txt   --input ${HOME}/dog.jpg   --output dog_result.jpg
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
20.89 ms
6.89 ms
5.46 ms
5.21 ms
5.38 ms
-------RESULTS--------
No objects detected
```


@Namburger  Which open source  or colab version do you recommend? I also check the tutorials [here](https://github.com/google-coral/tutorials/blob/master/retrain_detection_qat_tf1.ipynb), but found it is the same as google coral guide.

**Comment by manoj7410** [comment]
Does this issue still persist ?

**Comment by manoj7410** [comment]
Feel free to reopen if the issue still persists.
