### ISSUE TITLE
Difference between a .tflite file and a .tflite file compiled for Edge TPU

### ISSUE THREAD

**Issue by Olivier-Dopeli** [google-coral/tflite#13]
Hello

I acquired the Coral Dev Board, and I am looking at the examples available on the Coral website.
And I wonder, how can I tell the difference between a .tflite file and a .tflite file compiled for Edge TPU?

Thank you in advance

**Comment by Namburger** [comment]
Hi Oliver, I  suggest using the tflite's [visualize](https://www.tensorflow.org/lite/guide/faq) tool or [netron](https://www.tensorflow.org/lite/guide/faq) to visualize the model.
Using one of our canned mobilenet v2 ssd as an example, a `netron` out put for the tflite model will shows all ops:
![t](https://user-images.githubusercontent.com/25712149/77925978-28374780-726b-11ea-97f4-9aa6b37f42c3.png)
Where as the same model after compiling for edgetpu will  be much smaller:
![e](https://user-images.githubusercontent.com/25712149/77926035-3d13db00-726b-11ea-8064-b07cac17581b.png)
There will be a `edgetpu-custom-op` replacing any ops that will be executed on the edgetpu!

**Comment by Olivier-Dopeli** [comment]
Hello,

Thank you for your reply. I was able to test the two methods (visualize tool and netron) and they allow a good visualization of the networks . 
With one of these two methods or another, is it possible to see the on-chip memory and off-chip memory allocation of the edge TPU from a _edgetpu.tflite file?

**Comment by Namburger** [comment]
@Olivier-Dopeli 
There isn't an api to query that at this time, unfortunately, but if you compile the model with the `-s` option, it should tells you the ops that will be on CPU vs TPU

**Comment by Ekta246** [comment]
@Namburger How do 

> Hi Oliver, I suggest using the tflite's [visualize](https://www.tensorflow.org/lite/guide/faq) tool or [netron](https://www.tensorflow.org/lite/guide/faq) to visualize the model.
> Using one of our canned mobilenet v2 ssd as an example, a `netron` out put for the tflite model will shows all ops:
> ![t](https://user-images.githubusercontent.com/25712149/77925978-28374780-726b-11ea-97f4-9aa6b37f42c3.png)
> Where as the same model after compiling for edgetpu will be much smaller:
> ![e](https://user-images.githubusercontent.com/25712149/77926035-3d13db00-726b-11ea-8064-b07cac17581b.png)
> There will be a `edgetpu-custom-op` replacing any ops that will be executed on the edgetpu!

Hi,
I have a .tflite model file for efficientdet-d0 . I was wondering how can I make it edge-tpu compiled?

**Comment by Namburger** [comment]
@Ekta246 Sorry for the late response here, did you get to check out the [edgetpu-compiler](https://coral.ai/docs/edgetpu/compiler/) documentation page?

**Comment by hjonnala** [comment]
Closing the issue as the original query got answered. Please feel free to reopen or create new issue if you are still facing issue to compile efficientdet-d0 to edgetpu-compiler.
