### ISSUE TITLE
lstpu README update

### ISSUE THREAD

**Issue by avrdct** [google-coral/tflite#15]
In the below documention , the binary location mentioned as `bazel-output`, but I think the binary is inside `bazel-bin`

cpp/examples/lstpu/README.md

Target //:lstpu up-to-date:
  bazel-bin/lstpu

**Comment by Namburger** [comment]
@avrdct thanks for watching out, the binary is actually in multiple locations but it's also in:
```
bazel-out/k8-opt/bin/lstpu
```
as specified in our [makefile rule](https://github.com/google-coral/tflite/blob/master/cpp/examples/lstpu/Makefile#L21)
