### ISSUE TITLE
whl file not supported

### ISSUE THREAD

**Issue by ncomly** [google-coral/tflite#17]
In following the coral board setup instructions, [step 4](https://coral.ai/docs/dev-board/get-started#6-run-a-model-using-the-tensorflow-lite-api), running the following command fails saying it "is not a supported wheel on this platform":
`pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_aarch64.whl`

All instructions on the coral board have been followed to this point without issue. I have also tried `python3 -m pip install` with no avail.

Do I need to change versions for pip or other? Is a different .whl needed? 
Any insight or fixes would be greatly appreciated!

Thanks!
-Nick

Tagging @petewarden as requested.

**Comment by Namburger** [comment]
Hi @ncomly can you share the outputs of these commands:
```
$ python3 --version
$ uname -a
```

**Comment by ncomly** [comment]
`> Python 3.5.3`

**Comment by Namburger** [comment]
@ncomly ahh, it's because you're trying to install the pip package for python3.7 but you have python 3.5. This should fix your issue:
```
$ pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp35-cp35m-linux_aarch64.whl
```

**On another note,** the Dev Board should comes with python3.7, I have a feeling that you've installed an older version of the OS. It shows that you are using kernel version `4.9.51` which was mendel3.0 (chef). I highly suggest re flashing the board with the newest image as [instructed here](https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image). The package you downloaded should be `mendel-enterprise-day-13.zip`.
For reference:
```
mendel@tuned-llama:~$ cat /etc/os-release 
PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
NAME="Mendel GNU/Linux"
ID=mendel
ID_LIKE=debian
HOME_URL="https://coral.withgoogle.com/"
SUPPORT_URL="https://coral.withgoogle.com/"
BUG_REPORT_URL="https://coral.withgoogle.com/"
VERSION_CODENAME="day"
```

**Comment by ncomly** [comment]
That did it. Thank you!

**Comment by namigalyv** [comment]
> @ncomly ahh, a couple things.
> 
> 1. The issue: you're trying to install the pip package for python3.7 but you have python 3.5. This should fix your issue:
> 
> ```
> $ pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp35-cp35m-linux_aarch64.whl
> ```
> 
> 1. The root of the issue: The Dev Board should comes with python3.7, I have a feeling that you've installed an older version of the OS. It shows that you are using kernel version `4.9.51` which was mendel3.0 (chef). I highly suggest re flashing the board with the newest image as [instructed here](https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image). The package you downloaded should be `mendel-enterprise-day-13.zip`.
> 
> For your reference:
> 
> ```
> mendel@tuned-llama:~$ cat /etc/os-release 
> PRETTY_NAME="Mendel GNU/Linux 4 (Day)"
> NAME="Mendel GNU/Linux"
> ID=mendel
> ID_LIKE=debian
> HOME_URL="https://coral.withgoogle.com/"
> SUPPORT_URL="https://coral.withgoogle.com/"
> BUG_REPORT_URL="https://coral.withgoogle.com/"
> VERSION_CODENAME="day"
> mendel@tuned-llama:~$ uname -a
> Linux tuned-llama 4.14.98-imx #1 SMP PREEMPT Wed Apr 29 14:43:45 UTC 2020 aarch64 GNU/Linux
> ```

Hi @Namburger , this doesn't work for me.

My references 

`mendel@arid-goose:~$ python3 --version`
`Python 3.5.3`

`mendel@arid-goose:~$ uname -a`
`Linux arid-goose 4.9.51-imx #1 SMP PREEMPT Thu Jan 31 01:58:26 UTC 2019 aarch64 GNU/Linux`

`mendel@arid-goose:~$ cat /etc/os-release`
`PRETTY_NAME="Mendel GNU/Linux 2 (Beaker)"`
`NAME="Mendel GNU/Linux"`
`VERSION_ID="2"`
`VERSION="2 (beaker)"`
`ID=mendel`
`ID_LIKE=debian`
`HOME_URL="https://aiyprojects.withgoogle.com/"`
`SUPPORT_URL="https://aiyprojects.withgoogle.com/"`
`BUG_REPORT_URL="https://aiyprojects.withgoogle.com/"`

I use this command : `$ pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp35-cp35m-linux_aarch64.whl`

And I got this error.
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4n9t0sfi/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4eb5iw0x-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-4n9t0sfi/numpy/`

Thanks.

**Comment by Namburger** [comment]
You are using a very very old version of MendelOS, maybe you followed an outdated tutorial?
I suggest you flash the newest image: https://coral.ai/docs/dev-board/reflash/#update-your-dev-board-with-apt-get

**Comment by namigalyv** [comment]
Thanks your comment.
Yes, my mendelOS very old. Unfortunately, I followed this tutorial.
https://medium.com/@aallan/hands-on-with-the-coral-dev-board-adbcc317b6af

I can't update mendelOS because `mdt devices` can't find any devices.
and I read this comment : https://medium.com/@Igor.Alovert/beware-these-instructions-use-an-older-release-of-mendel-linux-beaker-18-ab7fa57cb930

is that true? I really have no chance to update?

**Comment by Namburger** [comment]
@namigalyv fortunately, you won't need `mdt` for that :)
just do (make sure the USB-A - USB-micro-B is plugged in)
```
screen /dev/ttyUSB<your-device-id> 115200
```
that'll get you to the serial console of the dev board, username and password are both `mendel`.
Then you can reboot the board into fastboot mode with:
```
sudo reboot-bootloader
```
And now your board is ready to be flashed with the new image!

**Comment by namigalyv** [comment]
@Namburger It works!
Thank you very much for your help :)

`mendel@jumbo-zebra:~$ cat /etc/os-release`
`PRETTY_NAME="Mendel GNU/Linux 4 (Day)"`
`NAME="Mendel GNU/Linux"`
`ID=mendel`
`ID_LIKE=debian`
`HOME_URL="https://coral.withgoogle.com/"`
`SUPPORT_URL="https://coral.withgoogle.com/"`
`BUG_REPORT_URL="https://coral.withgoogle.com/"`
`VERSION_CODENAME="day"`

I'm very appreciative!

**Comment by sterlingrpi** [comment]
Hi all

I just flashed my TPU dev board today following the instructions from https://coral.ai/docs/dev-board/get-started/ and I also cannot get tflite_runtime to install or work. I too have Python 3.5.3 and Linux/Mendel 4.9.51. I flashed from https://dl.google.com/coral/mendel/enterprise/mendel-enterprise-day-13.zip as per the instructions.

The update instructions provided by @Namburger https://coral.ai/docs/dev-board/reflash/#flash-a-new-system-image also show https://dl.google.com/coral/mendel/enterprise/mendel-enterprise-day-13.zip so updating to that would be the same version of Mendel I think?

How should I update my TPU dev board so it can do the gradient decent things?
