### ISSUE TITLE
abnormal inference speed on rpi 3b using usb accelerator

### ISSUE THREAD

**Issue by natxopedreira** [google-coral/tflite#18]
Hello

Im running a raspbery pi3b with Buster, python 3.7 and fresh usb accelerator install
[https://coral.ai/docs/accelerator/get-started/ ](https://coral.ai/docs/accelerator/get-started/ )

pip3 freeze result
`tflite-runtime==2.1.0.post1`

Im running this example
[https://github.com/google-coral/tflite/tree/master/python/examples/detection](https://github.com/google-coral/tflite/tree/master/python/examples/detection)

And in the page is mentioned this benchmark as reference
-------------------------------------------------------------------------------------
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
33.92 ms
19.71 ms
19.91 ms
19.91 ms
19.90 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=228, ymin=421, xmax=293, ymax=545)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=513, ymax=596)

But im getting a much slower inferece speed
-------------------------------------------------------------------------------------
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
276.87 ms
75.67 ms
75.27 ms
74.61 ms
74.14 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=226, ymin=417, xmax=290, ymax=539)
person
  id:     0
  score:  0.83984375
  bbox:   BBox(xmin=2, ymin=5, xmax=507, ymax=590)

**Comment by natxopedreira** [comment]
i will post it on edgetpu repo seems more logical

**Comment by Namburger** [comment]
@natxopedreira which model did you run?

**Comment by natxopedreira** [comment]
Sorry i closed this as i posted on the other repo, i reply to you in the other one
[https://github.com/google-coral/edgetpu/issues/115](https://github.com/google-coral/edgetpu/issues/115)

Thanks
