### ISSUE TITLE
RuntimeError: Internal: Unsupported data type: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

### ISSUE THREAD

**Issue by james-bjss** [google-coral/tflite#21]
Hi, When testing out my USB Coral device on Windows10 executing the classification example results in the following error:

`c:\Users\James\tampopo\tf\coral\tflite\python\examples\classification>python classify_image.py --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels models/inat_bird_labels.txt --input images/parrot.jpg
Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 100, in main
    interpreter.allocate_tensors()
  File "C:\Users\James\AppData\Local\Programs\Python\Python37\lib\site-packages\tflite_runtime\interpreter.py", line 243, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "C:\Users\James\AppData\Local\Programs\Python\Python37\lib\site-packages\tflite_runtime\tensorflow_wrap_interpreter_wrapper.py", line 110, in AllocateTensors
    return _tensorflow_wrap_interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.`

**Further details:**
Python Version: Python 3.7.8rc1
tflite Runtime: tflite_runtime-2.1.0.post1-cp37-cp37m-win_amd64.whl
edgetpu wheel: edgetpu-2.14.0-cp37-cp37m-win_amd64.whl
Driver Package: 2.14.1 (Jun 2020) edgetpu_runtime_20200624.zip

Relates to: #9

**Comment by james-bjss** [comment]
It seems like reverting to older drivers (`2.13.0 (Jan 2020)`) resolved this issue.
However I was simply following the setup guide https://coral.ai/docs/accelerator/get-started/ which links to the latest 2.14.0 drivers and suggests running this example so others may fall foul of this.

**Comment by Namburger** [comment]
Hey, `2.14.1` should have been the same as `2.14` with added window supports. This issue is not expected, but please allow me to check with my team. I guess the added supports for pcie must have caused this, another user have experienced the same: https://github.com/google-coral/tflite/issues/16#issuecomment-651078588

**Comment by james-bjss** [comment]
> Hey, `2.14.1` should have been the same as `2.14` with added window supports. This issue is not expected, but please allow me to check with my team. I guess the added supports for pcie must have caused this, another user have experienced the same: [#16 (comment)](https://github.com/google-coral/tflite/issues/16#issuecomment-651078588)
> 
> Could you try upgrading to `2.14` (without the `.1`)?

Sure, will try this evening and report back.

**Comment by james-bjss** [comment]
@Namburger - I can confirm that `2.14.0` is also working. So is just `2.14.1` that is affected.

**Comment by Namburger** [comment]
@james-bjss perfect, thanks for confirmation, I'll report this with our team

**Comment by Namburger** [comment]
@james-bjss as it turned out, we uploaded the wrong zipfile for that link :)
We just updated it, everything should works now if you redownload the zip file for `1.14.1`!

**Comment by james-bjss** [comment]
@Namburger - Oops! Just tested with the new Zip and it's working fine. Think this one can be closed now. Thanks for your help.

**Comment by Namburger** [comment]
Perfect! Thanks for confirmation :)
