### ISSUE TITLE
Can’t Run a Coral EdgeTPU classification model with TFLite API

### ISSUE THREAD

**Issue by ssghost** [google-coral/tflite#22]
I am trying to apply the tutorial of coral USB accelerator with MacOS 10.15. The tutorial link : [Get started with the USB Accelerator](https://coral.ai/docs/accelerator/get-started/#requirements)

Everything is successfully done until the last step "Run the image classifier with the bird photo (shown in figure 1)"

I copied the code to my terminal:
`` python3 classify_image.py \
--model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
--labels models/inat_bird_labels.txt \
--input images/parrot.jpg ``

My terminal returns this error information:
`` Traceback (most recent call last):
  File "classify_image.py", line 122, in <module>
    main()
  File "classify_image.py", line 99, in main
    interpreter = make_interpreter(args.model)
  File "classify_image.py", line 73, in make_interpreter
    {'device': device[0]} if device else {})
  File "/Users/xxx/anaconda3/lib/python3.6/site-packages/tflite_runtime/interpreter.py", line 204, in __init__
    model_path, self._custom_op_registerers))
SystemError: <built-in function InterpreterWrapper_CreateWrapperCPPFromFile> returned a result with an error set ``

How should I fix it?

**Comment by Namburger** [comment]
Can you share the outputs of these commands?
```
python3 -c 'print(__import__("tflite_runtime").__git_version__)'
python3 -c "from ctypes import *; cdll.LoadLibrary('libedgetpu.so.1.0'); print('success')" 
```

**Comment by ssghost** [comment]
``python3 -c 'print(__import__("tflite_runtime").__git_version__)'
>>> '0.6.0-76902-gd855adfc5a'``
``python3 -c "from ctypes import *; cdll.LoadLibrary('libedgetpu.so.1.0'); print('success')" 
>>> OSError: dlopen(libedgetpu.so.1.0, 6): image not found``
``md5sum /usr/local/lib/libedgetpu.1.0.dylib
a8a47d9dc537bd56c77cc5c7cb4e6aa6  /usr/local/lib/libedgetpu.1.0.dylib``

**Comment by ssghost** [comment]
Although I still don't know the reason, today when I run the command again on the same computer, it worked well as the webpage described. So please close this Issue thread.

**Comment by Namburger** [comment]
@ssghost Ahh, I was trying to check if the correct version of `/usr/local/lib/libedgetpu.1.0.dylib` was installed on our system. 
But from your outputs, everything looks good :)
