### ISSUE TITLE
Coral Detection Demo wrong  tflite file 

### ISSUE THREAD

**Issue by mwkldeveloper** [google-coral/tflite#24]
In the detection example, install_requirements.sh indicate wrong tflite file, which is 404 not found:
```
(cd "${MODEL_DIR}"
curl -OL "${TEST_DATA_URL}/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite" \
     -OL "${TEST_DATA_URL}/mobilenet_ssd_v2_coco_quant_postprocess.tflite" \
     -OL "${TEST_DATA_URL}/coco_labels.txt")
```

It cause error when try the example:
![image](https://user-images.githubusercontent.com/8042599/87382535-c5737d00-c5c9-11ea-9140-a74497b6ba61.png)

Correct tflite file should be:
![image](https://user-images.githubusercontent.com/8042599/87382459-92c98480-c5c9-11ea-8451-0c01cdabd0e8.png)
[https://github.com/google-coral/edgetpu/tree/master/test_data](https://github.com/google-coral/edgetpu/tree/master/test_data)

ssd_mobilenet_v2_coco_quant_postprocess.tflite
ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite

**Comment by Namburger** [comment]
Thanks, will get this fixed!

**Comment by Namburger** [comment]
@yaotechiu sorry, this is already fixed for us internally, will push it out in next release

**Comment by dudqls1994** [comment]
> @yaotechiu sorry, this is already fixed for us internally, will push it out in next release
![image](https://user-images.githubusercontent.com/19822691/94242633-4f887c00-ff51-11ea-9dc9-1b75b3ed0655.png)

Is this problem is solved??? 
I faced the same error.

**Comment by Namburger** [comment]
@dudqls1994 the solution is to change mobilenet_ssd to sss_mobilenet in the installation script and when running the model. We are in a middle of a big release and all these changes are expected in mid q4

**Comment by geogeorgiev** [comment]
> > @yaotechiu sorry, this is already fixed for us internally, will push it out in next release
> > ![image](https://user-images.githubusercontent.com/19822691/94242633-4f887c00-ff51-11ea-9dc9-1b75b3ed0655.png)
> 
> I use /mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite this model!
> Is this problem is solved???
> I faced the same error.

I solved this issue. It happens when downloading the `.tflite` from a device where you are not logged in to github (e.g. raspberry pi). In this case the file you download is an `html` text file (hence <!D, part of <!Doctype><html>...) *instead of the buffer file* holding the model. 

Solution: I just downloaded the `.tflite` model file on my workstation where I am logged in and transferred the file to the device where the demo is run.

**Comment by manoj7410** [comment]
This has been fixed. Feel free to reopen this thread if you still face the issue.
