### ISSUE TITLE
Failed to update the Coral Debian package

### ISSUE THREAD

**Issue by txloc1909** [google-coral/tflite#29]
I'm setting up a RPi 4 & Coral Edge TPU USB Accelerator, follow the guide at https://coral.ai/docs/accelerator/get-started
After adding the Debian package & the apt-key and run `sudo apt-get update`, I got this error message:

`W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://storage.googleapis.com/bazel-apt stable InRelease: The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>
W: Failed to fetch https://storage.googleapis.com/bazel-apt/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 3D5919B448457EE0 Bazel Developer (Bazel APT repository key) <bazel-dev@googlegroups.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.`

Continue with the guide, it failed when I run the classification example
`ValueError: Failed to load delegate from libedgetpu.so.1`

**Comment by Namburger** [comment]
Hey Lộc :)
There must have been an issue with our apt server, are you downloading this in Việt Nam?
`ValueError: Failed to load delegate from libedgetpu.so.1` means that you haven't been able to install our library.
Can you try the `sudo apt update` again? If it still doesn't work, do this:
```
REMOVE APT SOURCE
$ rm /etc/apt/sources.list.d/coral-edgetpu.list
$ apt update
DIRECT DOWNLOAD
$ curl -O https://dl.google.com/coral/edgetpu_api/edgetpu_runtime_20200728.zip
$ unzip edgetpu_runtime_20200728.zip && cd edgetpu_runtime_20200728
$ sudo ./install.sh
This step should be defaulted but will add, just in case:
$ sudo usermod -a -G plugdev $USER
$ sudo reboot now
```

**Comment by Namburger** [comment]
Hi, any updates?

**Comment by txloc1909** [comment]
Hi Nam, 
Sorry for the late reply.

Following your help, I was able to resolve the problem.

FYI, the Raspberry Pi is located in Japan. In Viet Nam, this problem does not occurs.

**Comment by Namburger** [comment]
@txloc1909 thanks for the update!
