### ISSUE TITLE
macosx_10_14_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by robmarkcole** [google-coral/tflite#31]
On attempting install `pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-macosx_10_14_x86_64.whl` on a Mac with Catalina 10.15.5 I receive the error: `ERROR: tflite_runtime-2.1.0.post1-cp37-cp37m-macosx_10_14_x86_64.whl is not a supported wheel on this platform.`
Presumably this is due to the updated OS? Some guidance on this in the docs would be great, updated wheels even better.
Thanks

**Comment by Namburger** [comment]
Hey @robmarkcole! 
We currently only have released package for Macos 10.14 (Mojave), let ping my team in a little bit to find out what's the plan for Mac Catalina support

This may take a while, but until then you can try building your own package using this instruction: https://github.com/google-coral/edgetpu/issues/198#issuecomment-674094275

**Comment by Namburger** [comment]
@robmarkcole update: for official release, a realistic timeline is in Oct when we will have this package available for Mac Catalina

**Comment by robmarkcole** [comment]
@Namburger thanks for the update on the timeline

**Comment by manoj7410** [comment]
macosx_10_15 can be found at https://github.com/google-coral/pycoral/releases/
