### ISSUE TITLE
semantic segmentation using TFLite API

### ISSUE THREAD

**Issue by pranavgundewar** [google-coral/tflite#32]
As mentioned, looking forward to Semantic Segmentation using TFLite API

**Comment by Namburger** [comment]
This is in the work, for now maybe you can look here: 
https://github.com/google-coral/edgetpu/blob/master/examples/semantic_segmetation.py

**Comment by hjonnala** [comment]
Here is the example with PyCoral API: https://github.com/google-coral/pycoral/blob/master/examples/semantic_segmentation.py

Feel free to reopen if you have any questions.
