### ISSUE TITLE
Running UNet with tflite_runtime

### ISSUE THREAD

**Issue by ItsMeTheBee** [google-coral/tflite#48]
Hey there!

I've trained a UNet model following these [instructions](https://colab.research.google.com/drive/1CCSM2FLOtHx0dPr1HgHFX0yLAgpOs7eT?usp=sharing#scrollTo=unP3cnxo_N72) but with two classes instead of three. I've also converted the network to tflite and compiled it with the coral edge compiler, but when I try to invoke the interpreter I get this error: ` Didn't find op for builtin opcode 'TRANSPOSE_CONV' version '3'`

Do you happen to have an example code of running UNet with tflite_runtime, similar to the code in this repo? I know pycoral exists but I need to run everything on an aarch64 system which is why I'm very hesitant to change to another library.

Best regards,
Sally

**Comment by hjonnala** [comment]
@ItsMeTheBee please share the invoking the interpreter script to reproduce the issue.

**Comment by ItsMeTheBee** [comment]
@hjonnala  here you go =)


```
import numpy as np
import tflite_runtime.interpreter as tflite
import sys
from time import time

import random

EDGETPU_SHARED_LIB = "libedgetpu.so.1"
DEBUG = True

def make_interpreter(model_path, edge_tpu=False):
    # Load the TF-Lite model and delegate to Edge TPU
    if edge_tpu:
        interpreter = tflite.Interpreter(model_path=model_path,
                experimental_delegates=[
                    tflite.load_delegate(EDGETPU_SHARED_LIB)
                    ])
    else:
        interpreter = tflite.Interpreter(model_path=model_path)

    return interpreter


def main(args=None):
    make_interpreter("/mnt/Storage/training/unet_multi_class/Multiclass-Segmentation-in-Unet/conversion/model_256x256.tflite", False)

if __name__ == '__main__':
    main()
```

I'm currently working with Python 3.6 and tflite_runtime 2.1.0. I'm guessing I either need to upgrade/ downgrade something or to specify the transpose_conv operator version.

**Comment by hjonnala** [comment]
The script is working fine for me with edgetpu output form shared colab notebook. 
Is the error coming with model_256x256_edgetpu.tflite? If yes, please share model_256x256_edgetpu.tflite file.

**Comment by ItsMeTheBee** [comment]
Huh interesting, could it be an issue because I am training and converting with TensorFlow 2.3.0 instead of nightly?
The model file can be downloaded from my private Google Drive: [here](https://drive.google.com/file/d/1wYuux86Q0jqdf1T31vZwrRMOoxPETmbu/view?usp=sharing).

**Comment by hjonnala** [comment]
Hello, I am using python 3.8 and corresponding tflite_runtime whl package from this source: https://github.com/google-coral/pycoral/releases

In my case correct whl would be: https://github.com/google-coral/pycoral/releases/download/v1.0.1/tflite_runtime-2.5.0-cp38-cp38-linux_x86_64.whl

The script is working fine with both True and False flags.

can you please share detail error message.
![Screenshot from 2021-07-13 06-41-45](https://user-images.githubusercontent.com/86132058/125462216-d2e2068d-5a90-4bd5-8de2-3f6930ba0a8e.png)

**Comment by ItsMeTheBee** [comment]
Ah sweet, it seems like it was an issue with my conda enviroment! I made a new one with Python 3.8 and it worked fine, made another one with Python 3.6 and that one worked as well :D

Thanks a lot!

Do you happen to have some code sample on how to use UNet with tflite_runtime? I'm guessing the image needs to be converted into a numpy array just like during the training (so with normal tensorflow and keras) or are there any differences?

**Comment by hjonnala** [comment]
May be this [https://github.com/google-coral/edgetpu/issues/417#issue-940647083](sample) helpful.
