### ISSUE TITLE
Coral is not speeding up the detection

### ISSUE THREAD

**Issue by DebojitBiswas** [google-coral/tflite#5]
Hi Team,

I was using webcam for detection problem. I used most of the code and changed a bit for the detection model using webcam. But "Coral" is not speeding up the detection. Without coral, I was getting 4 FPS and with coral also it is the same. I used [https://coral.withgoogle.com/docs/accelerator/get-started#requirements](url) to setup the "Coral stick".

My code has <def make_interpreter(model_file):
  model_file, *device = model_file.split('@')
  return tflite.Interpreter(
      model_path=model_file,
      experimental_delegates=[
          tflite.load_delegate(EDGETPU_SHARED_LIB,
                               {'device': device[0]} if device else {})
      ])>
And it runs fine without throging the error. Could you help please?

**Comment by Namburger** [comment]
@DebojitBiswas 
This is possibly related to this:
https://github.com/google-coral/edgetpu/issues/18

Did you run the model through the edgetpu_compiler? If so can you share the log?

**Comment by DebojitBiswas** [comment]
Thank you for updating. I found the issue. I was running "tflite" model, whereas  I should run "Edge TPU model".
