### ISSUE TITLE
can not open resized_cat.bmp

### ISSUE THREAD

**Issue by tyouritsugun** [google-coral/tflite#51]
Hi, 

I was trying classify.cc, I am using resized_cat.bmp from

https://github.com/google-coral/edgetpu/tree/master/test_data

However, I got the error below:

```
Cannot read image from /path/to/images/resized_cat.bmp
```
When I trace to the source, I found in line 54 of classify.cc
```
Line 53: int width = ToInt32(&info_header[4]);
Line 54: if (width < 0) return {};  // Invalid width.
```
The debugger says that the width  is -32.

Please tell me where can I get the correct BMP file or is there any bug in `ReadBmpImage`?

Thank you in advance
Zhang

**Comment by manoj7410** [comment]
@tyouritsugun What is the PATH that you have provided for resized_cat.bmp ? Is an image available at that PATH ?

**Comment by tyouritsugun** [comment]
Hi

Thank you for your reply. 

The line below

```
std::ifstream file(filename, std::ios::binary);
```
succeeded.

When I debug the `filename`, it is correct file name located in the directory I placed it to.

The problem might be the BMP info header parsing, the program says that the width of `resized_cat.bmp` is -32 but not 224 which is unexpected.

Zhang

**Comment by manoj7410** [comment]
@tyouritsugun Did you try with any other image as well ?

**Comment by tyouritsugun** [comment]
Here is my system information:
OS: Ubuntu 20.04
IDE: VS code 1.61.1
CPU: X64
TPU: Coral USB Accelerator

Zhang

**Comment by tyouritsugun** [comment]
C

> @tyouritsugun Did you try with any other image as well ?

Can you please give a link to make sure that we are talking about the same image?
Regards
Zhang

**Comment by manoj7410** [comment]
Can you try with https://github.com/google-coral/edgetpu/blob/master/test_data/parrot.jpg ?

**Comment by tyouritsugun** [comment]
> Can you try with https://github.com/google-coral/edgetpu/blob/master/test_data/parrot.jpg OR https://raw.githubusercontent.com/google-coral/edgetpu/master/test_data/cat.bmp ?

the former one, jpg guy:
it returns from line 41:
`return {};  // Invalid file type.`

the latter one, bmp guy:
`const uint32_t offset = ToInt32(&file_header[10]);` says that the offset is 4294967178.
`int width = ToInt32(&info_header[4]);` says that the width is 512
`int height = ToInt32(&info_header[8]);` says that the height is 341
then, it returns from line 67:
`return {};  // Read failed.`

Hope those information are helpful.

Regards
Zhang

**Comment by hjonnala** [comment]
@tyouritsugun can you please share the binary file for classify.cc.

Please try the [classsify_image.cc](https://github.com/google-coral/libcoral/blob/master/coral/examples/classify_image.cc) also from [libcoral](https://github.com/google-coral/libcoral) repo.

**Comment by hjonnala** [comment]
Please try this command if you are using linux machine to resize image:

` convert cat.bmp -resize 224x224! resize_cat.bmp`

Feel free to reopen if you still having any issues. Thanks!

**Comment by rfried-nrl** [comment]
I'm experiencing the same.
Ubuntu 21.04

Tried resizing using the command above. didn't work.
