### ISSUE TITLE
Calling `make_interpreter()` crashes the sample `classify_image.py` script with no error message

### ISSUE THREAD

**Issue by talcs** [google-coral/tflite#53]
### Description

Hello,

I have a Windows 10 machine and I could only execute the Coral example using the old drivers (edgetpu_runtime_20210119), which caused abnormal runtimes of ~1800ms per image.

Later, I fixed the `install.bat` script in the latest version (edgetpu_runtime_20210726):

### Before change

    start /wait msiexec /i "%ROOTDIR%\third_party\usbdk\UsbDk_*.msi" /quiet /qb! /norestart

### After change

    start /wait msiexec /i "%ROOTDIR%\third_party\usbdk\UsbDk_1.0.22_x64.msi" /quiet /qb! /norestart

Now the `failed to load delegate from edgetpu.dll` error message has disappeared, yet a new error started appearing, where the script hangs up with no error message when it calls `interpreter = make_interpreter(*args.model.split('@'))`.

### Insights
* It appears that it hangs when it calls: `return tflite.load_delegate(_EDGETPU_SHARED_LIB, options or {})`.
* The 3rd party `libusb-1.0.dll` file of the latest edgetpu_runtime release makes the problems. If I copy the file from the 20210119 version to `C:\Windows\System32`, then I fallback to the previous problem of very slow model execution.

Any advice?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install, Support

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hi,  in this [issue](https://github.com/google-coral/tflite/issues/52#issue-1029196337) you are trying with cpu tflite model. Can you please try with `mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite`.

**Comment by talcs** [comment]
Wow, thanks! I'm pretty shocked... wasn't aware of the fact that there were two files with similar names.

The updated output:

    C:\programs\coral\pycoral>python .\examples\classify_image.py --model .\test_data\mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite --labels .\test_data\inat_bird_labels.txt --input .\test_data\parrot.jpg
    ----INFERENCE TIME----
    Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
    14.4ms
    4.8ms
    4.9ms
    4.8ms
    4.7ms
    -------RESULTS--------
    Ara macao (Scarlet Macaw): 0.76953

Problem's solved 😃
