### ISSUE TITLE
can not open resized_cat.bmp v2

### ISSUE THREAD

**Issue by rfried-nrl** [google-coral/tflite#56]
### Description

Like #51 I experience the same.
The example application classify.cc fails reading the resized_cat.bmp

$ ./classify mobilenet_v1_1.0_224_quant_edgetpu.tflite imagenet_labels.txt resized_cat.bmp 0.0001
Cannot read image from resized_cat.bmp

$ convert cat.bmp -resize 224x224! resize_cat.bmp
$ file resize_cat.bmp
resize_cat.bmp: PC bitmap, Windows 98/2000 and newer format, 224 x 224 x 32

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Ubuntu

### Coral Device

M.2 Accelerator B+M

### Programming Language

C++

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Hello @rfried-nrl please try classify_image.cc form libcoral repo: https://github.com/google-coral/libcoral/tree/master/coral/examples

and here is a example on how to build your custom script: https://github.com/google-coral/edgetpu/issues/600#issuecomment-1145076778

Thanks!
