### ISSUE TITLE
Add support for python 3.10 for TFLite_runtime and PyCoral

### ISSUE THREAD

**Issue by feranick** [google-coral/tflite#58]
### Description

Currently the provided whl files are only for python 3.9 and below. Python 3.10 is the current stable version of Python and it is what ships with the LTS versions of Ubuntu and Debian. The lack of whls for TFLite_runtime and PyCoral makes any coral device useless with any system using Python 3.10.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Operating System

Windows 10, Linux, Ubuntu, Mac OS

### Programming Language

Other

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Closing the issue here as we have duplicate issue at: https://github.com/google-coral/pycoral/issues/58
