### ISSUE TITLE
Same predicted score for various oobjects

### ISSUE THREAD

**Issue by DanilZittser** [google-coral/tflite#59]
### Description

Hi to all!

Why model often predict same score for various objects?

Below code snippet from detection README.md
```
INFO: Initialized TensorFlow Lite runtime.
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
33.92 ms
19.71 ms
19.91 ms
19.91 ms
19.90 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375  # <--- this
  bbox:   BBox(xmin=228, ymin=421, xmax=293, ymax=545)
person
  id:     0
  score:  0.83984375    # <--- this
  bbox:   BBox(xmin=2, ymin=5, xmax=513, ymax=596)
```

I have a similar situation in my custom dataset: many identical scores.

![02-custom](https://user-images.githubusercontent.com/51195714/180185024-82c479a6-0a79-4d21-9d23-b1216f15f367.png)
![01-original](https://user-images.githubusercontent.com/51195714/180185031-eda2c6d7-7fc1-4b43-8f90-26891dc25417.png)

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Operating System

Mendel Linux

### Coral Device

Dev Board

### Programming Language

Python 3.7

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
Can you please point me to the source of edgetpu model you are using and try the below steps:

```
git clone https://github.com/google-coral/pycoral.git

cd pycoral

bash examples/install_requirements.sh detect_image.py

mendel@queen-shrimp:~/pycoral$ python3 examples/detect_image.py   --model test_data/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite   --labels test_data/coco_labels.txt   --input test_data/grace_hopper.bmp   --output ${HOME}/grace_hopper_processed.bmp
----INFERENCE TIME----
Note: The first inference is slow because it includes loading the model into Edge TPU memory.
41.56 ms
16.21 ms
15.27 ms
13.50 ms
15.66 ms
-------RESULTS--------
tie
  id:     31
  score:  0.83984375
  bbox:   BBox(xmin=227, ymin=419, xmax=292, ymax=541)
person
  id:     0
  score:  0.8046875
  bbox:   BBox(xmin=2, ymin=4, xmax=513, ymax=595)

```

**Comment by DanilZittser** [comment]
Thanks!

I get the same result as you:
![Screenshot_20220727_201302](https://user-images.githubusercontent.com/51195714/181308714-501049e7-406f-4d3b-9fdb-e53ead4fee6d.png)

But in detection [README.md](https://github.com/google-coral/tflite/tree/master/python/examples/detection#run-the-code) the following problem:
![Screenshot_20220727_201705](https://user-images.githubusercontent.com/51195714/181309343-12173638-1a62-4b86-af9f-20ec4350778f.png)

What is the reason of this behavior?

**Comment by hjonnala** [comment]
It's because detection [README.md](https://github.com/google-coral/tflite/tree/master/python/examples/detection#run-the-code) is using the  old model from [edgetpu repo](https://github.com/google-coral/edgetpu/tree/master/test_data). Please get the updated models form [test_data repo](https://github.com/google-coral/test_data). Thanks!
