### ISSUE TITLE
Loading an edgetpu .tflite model with tensorflow.lite.Interpreter crashes

### ISSUE THREAD

**Issue by enricoschroeder** [google-coral/tflite#64]
### Description

I am trying to load an *edgetpu.tflite model (for example the supplied mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite or any other model I tried) with the regular tensorflow.lite.Interpreter and the edgetpu delegate. This silently crashes (I suspect a segmentation fault in the background). 

```python
import tensorflow as tf

# Program silently crashes while executing code below
edgetpu_interpreter = tf.lite.Interpreter('./mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite',
                                         experimental_delegates=[tf.lite.experimental.load_delegate('edgetpu.dll')])
```

I tried with tensorflow 2.10.0 and 2.12.0. I can load the same model on the same machine with tflite-runtime 2.5.0 without any problems, however I need regular Tensorflow for dataset operations in my code and both (tflite-runtime and regular tensorflow) cannot be imported at the same time. Since the tflite Interpreter is included in the regular tensorflow package (and I have seen recommendations of using it instead of the dedicated tflite-runtime package), I would assume that this should work, shouldn't it?

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Operating System

Windows 10

### Coral Device

USB Accelerator

### Programming Language

Python 3.9

### Relevant Log Output

_No response_</details>

**Comment by hjonnala** [comment]
@enricoschroeder our recommendation is to use  tflite-runtime 2.5.0.post1. If you would like use with tf 2.10, 2.12 or any other version, please build libedgetpu, pycoral and tflite_runtime pacakges for your platform, using the instructions at: https://coral.ai/docs/notes/build-coral/. Thanks!!

**Comment by enricoschroeder** [comment]
@hjonnala Thanks for the answer! Before I go down the rabbit hole to build everthing with a current tensorflow version: Am I right to expect that using the regular tensorflow.lite.Interpreter with a matching libedgetpu should work? 

Also, is there any particular reason why you do not provide more up-to-date versions of everything?

**Comment by hjonnala** [comment]
> @hjonnala Thanks for the answer! Before I go down the rabbit hole to build everthing with a current tensorflow version: Am I right to expect that using the regular tensorflow.lite.Interpreter with a matching libedgetpu should work?

Yes..
