### ISSUE TITLE
Cannot build lstpu successfully on Raspberry 3 model B

### ISSUE THREAD

**Issue by guomxin** [google-coral/tflite#8]
Raspberry Pi 3 Model B
OS: Raspbian(Buster)
Bazel: 0.26.0
GCC: 8.3.0

make CPU=armv7a，report following errors:
INFO: Analyzed target //:lstpu (7 packages loaded, 79 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/b74c6408939043eedfe3e11190196b71/external/org_tensorflow/tensorflow/lite/c/BUILD:6:1: undeclared inclusion(s) in rule '@org_tensorflow//tensorflow/lite/c:c_api_internal':
this rule is missing dependency declarations for the following files included by 'external/org_tensorflow/tensorflow/lite/c/c_api_internal.c':
  '/usr/lib/gcc/arm-linux-gnueabihf/8/include/stdbool.h'
  '/usr/lib/gcc/arm-linux-gnueabihf/8/include/stddef.h'
  '/usr/lib/gcc/arm-linux-gnueabihf/8/include/stdint.h'
  '/usr/lib/gcc/arm-linux-gnueabihf/8/include/stdarg.h'
Target //:lstpu failed to build

**Comment by Namburger** [comment]
@guomxin hi, are you trying to build from the rpi itselft?
This were meant to be cross compiled on an x86 host machine and then copy the binary over to the target machine for execution.

**Comment by guomxin** [comment]
@Namburger Thanks. Yes, i'm trying to build from the rpi. It's not expected, right?

**Comment by Namburger** [comment]
@guomxin yes, that isn't going to work!

**Comment by guomxin** [comment]
Got it. thanks. I have built successly on x86 host machine.
