### ISSUE TITLE
RuntimeError: Internal: Unsupported data type: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.

### ISSUE THREAD

**Issue by lsq314** [google-coral/tflite#9]
Hi all, 

I am using the Coral Dev Board with the Mendel OS 4.0 (Day) version and tflite_runtime version 2.1.0. However, when I run the following example (officially provided)
`python3 classify_image.py   --model models/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite   --labels models/inat_bird_labels.txt   --input images/parrot.jpg`
I get the following error message.
`Traceback (most recent call last):
  File "classify_image.py", line 122, in <module> 
main()
  File "classify_image.py", line 100, in main
    interpreter.allocate_tensors()
  File "/home/mendel/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 242, in allocate_tensors
    return self._interpreter.AllocateTensors()
  File "/home/mendel/.local/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 115, in AllocateTensors
    return _interpreter_wrapper.InterpreterWrapper_AllocateTensors(self)
RuntimeError: Internal: Unsupported data type: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.`

Meanwhile, when I run the detection's example. The error is similar. Could someone please figure this out?

**Comment by lsq314** [comment]
Plus, I could run the inference using the "edgetpu api" well.

**Comment by Namburger** [comment]
@lsq314 have you upgraded your libedgetpu runtime to version 13?

**Comment by lsq314** [comment]
@Namburger Yes. This is the output when I run `dpkg -l | grep edgetpu`. 
"ii  edgetpu                              13.0                        all          Edge TPU compiler and runtime
ii  edgetpu-compiler                     13.0                        arm64        Edge TPU model compiler
ii  edgetpudemo                          3-1                         all          Edge TPU demo script
ii  libedgetpu1-std:arm64                12-1                        arm64        Support library for Edge TPU
ii  python3-edgetpu                      12.1-1                      arm64        Edge TPU Python API
ii  python3-edgetpuvision                6-1                         arm64        EdgeTPU camera API
"

**Comment by Namburger** [comment]
Ahh, can you also upgrade `libedgetpu1-std` also?

**Comment by lsq314** [comment]
@Namburger I find that no. I will try this.

**Comment by lsq314** [comment]
@Namburger Thank you very much. It's been figured out.
